name: Generate EPG XML

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run script to generate EPG XML
        run: python malayalam.py

      - name: Commit and push if changed
        run: |
          git config --global user.email "mailmasterdlay@icloud.com"
          git config --global user.name "dLay-iOS"
          git add epg.xml
          git commit -m "Automatically update EPG XML" || exit 0   # This command will exit with 0 if there's nothing to commit
          git push https://${{ secrets.MY_PERSONAL_TOKEN }}@github.com/dLay-iOS/epg.git
